name: ç¼–è¯‘ & å‘å¸ƒ & éƒ¨ç½²

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'æ˜¯å¦ä½¿ç”¨ Maven ç¼“å­˜'
        required: true
        default: 'true'
#      re_chaos:
#        description: 'æ˜¯å¦é‡å‘ chaos'
#        required: true
#        default: 'true'
#      re_gateway:
#        description: 'æ˜¯å¦é‡å‘ gateway'
#        required: true
#        default: 'true'
#      re_sso_server:
#        description: 'æ˜¯å¦é‡å‘ sso-server'
#        required: true
#        default: 'true'
#      re_spring_boot_admin:
#        description: 'æ˜¯å¦é‡å‘ spring-boot-admin'
#        required: true
#        default: 'false'
#  push:
#    branches:
#      - develop
#      - rls-*
#      - features-*
#      - master
  create:
    tags:
      - v*.*.*

env:
  IMAGE_NAME: ${{ secrets.IMAGES_HUB_REGISTRY_URL }}/${{ secrets.IMAGES_HUB_NAMESPACES }}/demo
  IMAGES_HUB_REGISTRY_URL: ${{ secrets.IMAGES_HUB_REGISTRY_URL }}
  IMAGES_HUB_USER_NAME: ${{ secrets.IMAGES_HUB_USER_NAME }}
  IMAGES_HUB_PASSWORD: ${{ secrets.IMAGES_HUB_PASSWORD }}
  IMAGES_HUB_EMAIL: hocgin@gmail.com
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}


  IMAGE_CHAOS: ${{ secrets.IMAGES_HUB_REGISTRY_URL }}/${{ secrets.IMAGES_HUB_NAMESPACES }}/chaos
  IMAGE_GATEWAY: ${{ secrets.IMAGES_HUB_REGISTRY_URL }}/${{ secrets.IMAGES_HUB_NAMESPACES }}/gateway
  IMAGE_SSO_SERVER: ${{ secrets.IMAGES_HUB_REGISTRY_URL }}/${{ secrets.IMAGES_HUB_NAMESPACES }}/sso-server
  IMAGE_SPRING_BOOT_ADMIN: ${{ secrets.IMAGES_HUB_REGISTRY_URL }}/${{ secrets.IMAGES_HUB_NAMESPACES }}/spring-boot-admin

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      # æ‹‰å–ä»£ç 
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout
      # å˜é‡æå–
      - name: Prepare
        id: prep
        run: |
          ################
          # èŽ·å–é•œåƒä¿¡æ¯
          ################
          DOCKER_IMAGE=${{ env.IMAGE_NAME }}
          VERSION=noop
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          # echo ::set-output name=version::${VERSION}
          echo ::set-output name=version::sha-${GITHUB_SHA::8}
          # echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          ################
          # èŽ·å–åˆ†æ”¯ä¿¡æ¯
          ################
          ENV=none
          BRANCH_NAME=none

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          fi

          echo $BRANCH_NAME

          if [[ $BRANCH_NAME == develop ]]; then
            ENV=test
          elif [[ $BRANCH_NAME =~ ^rls-.* ]]; then
            ENV=rls
          elif [[ $BRANCH_NAME =~ ^features-.* ]]; then
            ENV=dev
          elif [[ $BRANCH_NAME == master || $BRANCH_NAME =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$  ]]; then
            ENV=prod
          fi

          echo ::set-output name=env::${ENV}
          echo ::set-output name=branch_name::${BRANCH_NAME}
          echo ::set-output name=tags::${BRANCH_NAME}

      # è®¾ç½® JDK çŽ¯å¢ƒ
      - name: Set up JDK 12.0
        uses: actions/setup-java@v1
        with:
          java-version: 12.0
      # ç¼“å­˜ Maven ä»“åº“
      - name: Cache local Maven repository
        if: ${{ github.event.inputs.use_cache != 'false' }}
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # è¿›è¡Œ Maven ç¼–è¯‘
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests --batch-mode
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # è®¾ç½® Docker ç¼–è¯‘çŽ¯å¢ƒ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # ç¼“å­˜ Docker å±‚
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # ç™»é™† é˜¿é‡Œäº‘å®¹å™¨é•œåƒä¸­å¿ƒ
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGES_HUB_REGISTRY_URL }}
          username: ${{ env.IMAGES_HUB_USER_NAME }}
          password: ${{ env.IMAGES_HUB_PASSWORD }}
      # ç¼–è¯‘å’Œå‘å¸ƒé•œåƒ => Gateway
      - name: Build & Push Docker Image::Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./rabbit-gateway
          file: ./rabbit-gateway/Dockerfile
          push: true
          tags: ${{ env.IMAGE_GATEWAY }}:${{ steps.prep.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
      # ç¼–è¯‘å’Œå‘å¸ƒé•œåƒ => Services::Chaos
      - name: Build & Push Docker Image::Chaos
        uses: docker/build-push-action@v2
        with:
          context: ./rabbit-services/rabbit-service-chaos/rabbit-service-chaos-start
          file: ./rabbit-services/rabbit-service-chaos/rabbit-service-chaos-start/Dockerfile
          push: true
          tags: ${{ env.IMAGE_CHAOS }}:${{ steps.prep.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
      # ç¼–è¯‘å’Œå‘å¸ƒé•œåƒ => Services::SSO-Server
      - name: Build & Push Docker Image::SSO-Server
        uses: docker/build-push-action@v2
        with:
          context: ./rabbit-sso-server
          file: ./rabbit-sso-server/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SSO_SERVER }}:${{ steps.prep.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
      # ç¼–è¯‘å’Œå‘å¸ƒé•œåƒ => Services::Spring-Boot-Admin
      - name: Build & Push Docker Image::Spring-Boot-Admin
        uses: docker/build-push-action@v2
        with:
          context: ./rabbit-spring-boot-admin
          file: ./rabbit-spring-boot-admin/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SPRING_BOOT_ADMIN }}:${{ steps.prep.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}

      # è®¾ç½® k8s çŽ¯å¢ƒ
      - name: Set up k8s Context
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ env.KUBE_CONFIG }}
      # é…ç½® å®¹å™¨ä¸­å¿ƒ è´¦å·/å¯†ç 
      - name: Create Container Registry Secret
        uses: Azure/k8s-create-secret@v1
        with:
          namespace: ${{ steps.prep.outputs.env }}
          container-registry-url: ${{ env.IMAGES_HUB_REGISTRY_URL }}
          container-registry-username: ${{ env.IMAGES_HUB_USER_NAME }}
          container-registry-password: ${{ env.IMAGES_HUB_PASSWORD }}
          container-registry-email: ${{ env.IMAGES_HUB_EMAIL }}
          secret-name: k8s-secret
      # éƒ¨ç½²åˆ° k8s
      - name: Deploy to k8s
        uses: Azure/k8s-deploy@v1
        with:
          namespace: ${{ steps.prep.outputs.env }}
          manifests: |
            manifests/deployment-gateway.yaml
            manifests/deployment-chaos.yaml
            manifests/deployment-sso-server.yaml
            manifests/deployment-spring-boot-admin.yaml
          images: |
            ${{ env.IMAGE_CHAOS }}:${{ steps.prep.outputs.version }}
            ${{ env.IMAGE_GATEWAY }}:${{ steps.prep.outputs.version }}
            ${{ env.IMAGE_SSO_SERVER }}:${{ steps.prep.outputs.version }}
            ${{ env.IMAGE_SPRING_BOOT_ADMIN }}:${{ steps.prep.outputs.version }}
          imagepullsecrets: |
            k8s-secret

      # ä¼ä¸šå¾®ä¿¡é€šçŸ¥
      - name: WeChat Work Notification
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "ðŸŽ‰ [Rabbit-Hole](https://github.com/tree-lotus/rabbit-hole) å‘å¸ƒå®Œæˆã€‚\n
          > \n
          ##### ä¿®æ”¹å†…å®¹ï¼š\n
          > ${{ github.event.head_commit.message }} \n
          ##### ä¿®æ”¹åˆ†æ”¯:\n
          > ${{ github.event.ref }} \n
          ##### ä¿®æ”¹æ—¶é—´:\n
          > ${{ github.event.head_commit.timestamp }} \n
          ##### ä¿®æ”¹äºº:\n
          > ${{ github.event.head_commit.committer.name }} \n
          > [æŸ¥çœ‹è¯¦æƒ…](https://www.hocgin.top)\n"
          mentioned_list: '["@all"]'
